import type { Metadata } from "next";
import Header from "./components/Header/Header";
import { WatchTogetherProvider } from "@/contexts/WatchTogetherContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <WatchTogetherProvider>
          {children}
        </WatchTogetherProvider>
      </body>
    </html>
  );
}
